olx/olx/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    #path('user/', include('django.contrib.auth.urls')),
   
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx/user/urls.py
from atexit import register
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView

# importing views from views..py
app_name = 'user'
urlpatterns = [
    path('', views.home,name="home"),
    path('signup/',views.signup,name='signup'),   
    path('send_otp', views.send_otp, name='sendOTP' ),
    path('login/',views.login,name='login'),
    #path('signup/validate_email/', views.validate_email, name='validate_email'),
    path('logout/',views.logout,name='logout'),
    path('verify_otp', views.verify_otp, name='verify_otp' ),
    path('confirm_user', views.confirm_user, name='confirm_user' ),
    path('forget_password', views.forget_password, name='forget_password' ),
    path('setPassword', views.setPassword, name='setPassword' ),
    path('reset', views.reset, name='reset' ),
    path('reset_password', views.reset_password, name='reset_password' ),
    path('profile/', views.profile, name='profile' ),
    path('setting/', views.setting, name='setting' ),
    path('add_product/', views.add_product, name='add_product' ),
    path('product_by_category/<pk>', views.product_by_category,name="product_by_category"),
   # path('delete_product/<product_id>', views.delete_product.as_view(), name='delete_product' ),
    path('<pk>/delete_product', views.Delete_product.as_view(), name='delete_product' ),
    path('detail_view/<pk>', views.detail_view, name='detail_view' ),
    path('<pk>/update_product', views.update_product, name='update_product' ),
    path('<int:user_id>/<int:room_name>/<int:sender_id>/', views.room, name='room'),
  #  path('', views.index, name='index'),
    path('subscription', views.subscription, name='subscription' ),
    path('subscription_process/<pk>', views.subscription_process, name='subscription_process' ),
    path('message', views.message, name='message' ),
    path('payment_done/', views.payment_done,name='payment_done'),
    path('payment_cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('seller_profile/<pk>', views.seller_profile, name='seller_profile' ),
    #path('search', views.SearchResultsView.as_view(), name='search_results'),
    path('search_product', views.search_product,name="search_product"),


    











   
] 

olx/user/models.py
from pyexpat import model
from sys import prefix
from unicodedata import category
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# Create your models here.
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from .managers import CustomUserManager
from django.utils import timezone



class CustomUser(AbstractBaseUser, PermissionsMixin):
    user_choice=(('buyer','Buyer'),('seller','Seller'),)
    email = models.EmailField(('email address'), unique=True)
    first_name = models.CharField(blank=True, max_length=150, verbose_name='first name')
    last_name = models.CharField(blank=True, max_length=150, verbose_name='last name')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    user_type = models.CharField(max_length=20, choices= user_choice , default='buyer')
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    # def save(self, *args, **kwargs):
    #     if not self.is_superuser:
    #         self.set_password(self.password)
    #         self.save()
    #     return super(CustomUser, self).save(force_insert=False,
    #                                   force_update=False,
    #                                   using=None,
    #                                   update_fields=None)


class EmailVerifyOtp(models.Model):
    email = models.EmailField(max_length=50, null=True, blank=True)
    otp = models.CharField(max_length=10, blank=True, null=True)


class Category(models.Model):
    categories=models.CharField(max_length=50,null=True, blank=True)
        
    def __str__(self):
        return self.categories

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_categories=models.CharField(max_length=50,null=True, blank=True)

    def __str__(self):
        return self.sub_categories

        
class Product(models.Model):
   
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    product_title=models.CharField(max_length=150,null=True, blank=True)
    product_description=models.CharField(max_length=150,null=True, blank=True)
    product_price=models.CharField(max_length=150,null=True, blank=True)
    product_location=models.CharField(max_length=150,null=True, blank=True)
    image=models.ImageField(upload_to='product_img',null=True, blank=True)

    def __str__(self):
        return self.product_title

    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product_img',null=True, blank=True)

    def __str__(self):
        return self.product.product_title

class SubscriptionBase(models.Model):
    subscription_choice=(('monthly','Monthly'),('annual','Annual'),)
    subscription = models.CharField(max_length=20, choices= subscription_choice,null=True, blank=True  )
    days=models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.subscription

class SubscriptionType(models.Model):
   # subscription_choice=(('monthly','Monthly'),('annual','Annual'),)
    name_choice=(('basic','Basic'),('standard','Standard'),('premium','Premium'))
   # subscription_name=  models.CharField(max_length=20, choices=  subscription_choice )
    package_name= models.CharField(max_length=20, choices= name_choice )
    price= models.FloatField(max_length=20, null=True, blank=True )
    ads_count=models.IntegerField(null=True, blank=True)
    subscription_name=models.ForeignKey(SubscriptionBase, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.package_name


class SubscriptionTransaction(models.Model):
    status_choice=(('initialized','Initialized'),('success','Success'),('failed','Failed')) 
    transaction_id=models.CharField(max_length=16,primary_key = True)
    amount= models.FloatField(max_length=20, null=True, blank=True )
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    transaction_status=models.CharField(max_length=20,choices=status_choice, default='initialized')
    invoice_id=models.CharField(max_length=16,null=True, blank=True)
    package=models.ForeignKey(SubscriptionType, on_delete=models.CASCADE,null=True)
    transaction_date=models.DateField(null=True,blank=True)

      

class UserSubscription(models.Model):
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    transaction=models.ForeignKey(SubscriptionTransaction,on_delete=models.CASCADE,null=True)
    purchase_date=models.DateField(null=True,blank=True)
    valid_till=models.DateField(null=True,blank=True)
    package=models.ForeignKey(SubscriptionType, on_delete=models.CASCADE,null=True)


class ChatRoom(models.Model):
    product_id=models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    buyer=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='buyer',null=True)
    seller=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='seller',null=True)


class ChatHistory(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    sender=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sender',null=True)
    message=models.CharField(max_length=500,null=True,blank=True)
    receiver=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='receiver',null=True)

olx/user/forms.py
# import the standard Django Forms
# from built-in library
from curses import meta
from pyexpat import model
from secrets import choice
from django import forms

from user.models import Product, Category, ProductImage, Subcategory



class InputForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Subcategory.objects.all())
    class Meta:
        model= Product
        fields = ['product_title', 'product_price','product_description','category','product_location','image']
    
   
class UpdateForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Subcategory.objects.all())
    class Meta:
        model= Product
        fields = ['product_title', 'product_price','product_description','category','product_location','image']


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')    
    class Meta:
        model = ProductImage
        fields = ('image', )

olx/user/templates/user/delete_product.html
{% extends "olx.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
     
    <p>Are you sure you want to delete "{{ object }}"?</p>
         
    <input type="submit" value="Confirm">
</form>


{% endblock %}

olx/user/templates/user/detail_view.html
{% extends "olx.html" %}
{% load static %}

{% block content %}
<style>
 

#content-wrapper{
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.column{
	width: 600px;
	padding: 10px;

}

#featured{
	max-width: 100%;
	max-height: 100%;
	object-fit: fill;
	cursor: pointer;
	

}

.thumbnail{
	object-fit: cover;
	max-width: 180px;
	max-height: 80px;
	cursor: pointer;
	opacity: 0.5;
	margin: 5px;
	

}

.thumbnail:hover{
	opacity:1;
}

.active{
	opacity: 1;
}

#slide-wrapper{
	max-width: 500px;
	display: flex;
	min-height: 100px;
	align-items: center;
}

#slider{
	width: 440px;
	display: flex;
	flex-wrap: nowrap;
	overflow-x: auto;

}

#slider::-webkit-scrollbar {
		width: 8px;

}

#slider::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);

}
 
#slider::-webkit-scrollbar-thumb {
  background-color: #dede2e;
  outline: 1px solid slategrey;
   border-radius: 100px;

}

#slider::-webkit-scrollbar-thumb:hover{
    background-color: #18b5ce;
}

.arrow{
	width: 30px;
	height: 30px;
	cursor: pointer;
	transition: .3s;
}

.arrow:hover{
	opacity: .5;
	width: 35px;
	height: 35px;
}
</style>



<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">{{products.product_title}}</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <!-- card for image -->
            <div class="col-md-8 mb-5 ">
              <div id="content-wrapper">
		

                <div class="column">
                  <img id=featured src='/media/{{products.image}}'>
              
                  <div id="slide-wrapper" >
                    <p id="slideLeft" class="arrow" style='font-size:50px;'>&#10096;</p>
              
                    <div id="slider">
                      
                      <img class="thumbnail active"  src='/media/{{products.image}}' width="100%">
                      {% for pi in products.productimage_set.all %}
                      <img class="thumbnail" src='/media/{{pi.image}}' width="100%">
                      
                      {% endfor %}
                    </div>
              
                    <p id="slideRight" class="arrow" style='font-size:50px;'> &#10097;</p> 
                  </div>
                </div>
              
                
              
              </div>
              <script type="text/javascript">
                let thumbnails = document.getElementsByClassName('thumbnail')
              
                let activeImages = document.getElementsByClassName('active')
              
                for (var i=0; i < thumbnails.length; i++){
              
                  thumbnails[i].addEventListener('mouseover', function(){
                    console.log(activeImages)
                    
                    if (activeImages.length > 0){
                      activeImages[0].classList.remove('active')
                    }
                    
              
                    this.classList.add('active')
                    document.getElementById('featured').src = this.src
                  })
                }
              
              
                let buttonRight = document.getElementById('slideRight');
                let buttonLeft = document.getElementById('slideLeft');
              
                buttonLeft.addEventListener('click', function(){
                  document.getElementById('slider').scrollLeft -= 180
                })
              
                buttonRight.addEventListener('click', function(){
                  document.getElementById('slider').scrollLeft += 180
                })
              
              
              </script>
              
              <br>
            <div class="row">
              <div class="card " style="background-color: rgb(255, 255, 255);">
                <div class="card-body" style="padding: 10px; ">
                    <div class="row">
                      <div class="col-md-9">
                        <h3>Details</h3>
                      </div>
                      <div class="col-md-3">
                        <h2><i style="font-size:24px" class="fa">&#xf156;</i>{{products.product_price}}</h2>
                      </div>
                    </div>
                  <hr>
                  <h4>{{products.product_title}}</h4>
                  <hr>
                  <h5>Description</h5>
                  <hr>
                  <p>{{products.product_description}}</p>
                 
                </div>
              </div>
            </div>
              <!-- <div class="about-product text-left mt-2"><img src='/media/{{products.image}}' style="width: 100%; height:250px">
                <div>
                    <h3><i style="font-size:24px" class="fa"></i>{{products.product_price}}</h3>
                    <h6 class="mt-0 text-black-50">{{products.product_title}}</h6>
                    
                </div>
            </div> -->
            </div>
            <div class="col-md-4">
              <div class="card mb-3">
                <div class="card-body" style="background-color: rgb(255, 255, 255);">
                  <h3 style="padding: 10px; ">Seller description</h3>
                  <hr>
                        <div class="card-body" style="padding: 10px;">
                          <div class="d-flex flex-column align-items-center text-center">
                            <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                              <h4>{{ products.owner.first_name}} {{ products.owner.last_name}}</h4>
                              <a href="{% url 'user:seller_profile' products.owner.id %}"  class="btn btn-primary">View Profile</a>
                              {% if user.is_authenticated %}
                              <a href="/{{products.owner.id}}/{{ products.id}}/{{ user.id }}" class="btn btn-primary">message</a>
                              {% else %}
                              <a href="/login" class="btn btn-primary">message</a>
                              {% endif %}


                              
                            </div>
                          </div>
                        </div>
                    
                  
                </div>
                <!-- user product -->
               
                <div class="card-body">
                  
                  <div class="row">
                  
                  
                   
                </div>



                </div>

              </div>

              



            </div>
          </div>

        </div>
    </div>



{% endblock %}

olx/user/templates/user/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

olx/user/templates/user/product_by_category.html
{% extends "olx.html" %}

{% block content %}

<div class="container">
    <nav aria-label="breadcrumb" class="main-breadcrumb">
      <ol class="breadcrumb">
        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">All Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
                     
          
          {% for cat in categorylist %}
          
          <li><a href="{% url 'user:product_by_category' cat.id %}" value="{{cat.id}}">{{cat.sub_categories}}</a></li>
          {% endfor %}
          
          
                  
    
          </ul>
        </li>
        <li class="breadcrumb-item active" aria-current="page">{{products.category.sub_categories}}</li>

      </ol>
    </nav>
    </div>
    <div class="container-fluid">
    <div class="row">

   console.log({{products.category.sub_categories}})

    {% for product in products %}
    <div class="col-md-2">
        <div class="mt-5">
          <div class="card">
              <div class="about-product text-left mt-2"><img src='/media/{{product.image}}' style="width: 100%; height:250px">
                <div class="card-body" style="padding: 10px; ">
                  <h3 class="card-title"><i style="font-size:24px" class="fa">&#xf156;</i>{{product.product_price}}</h3>
                      <!-- <h3><i style="font-size:24px" class="fa">&#xf156;</i>{{product.product_price}}</h3> -->
                      <h4 class="mt-0 text-black-50 card-text">{{product.product_title}}</h4>
                      <a href="{% url 'user:detail_view' product.id %}" class="btn btn-primary">View</a>
                  </div>
              </div>
              
            </div>   
        </div>
        </div>
{% endfor %}


</div>
</div>



{% endblock %}

olx/user/templates/user/profile.html
{% extends "olx.html" %}

{% block content %}
<!-- <!DOCTYPE html>
<html>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</head>
<body> -->
<!-- <ul>
    <li><a href="reset">reset password</a></li>
</ul> -->

<div class="container">
    <div class="main-body">
    
          <!-- Breadcrumb -->
          <nav aria-label="breadcrumb" class="main-breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">User Profile</li>
            </ol>
          </nav>
          <!-- /Breadcrumb -->
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ user.first_name}}</h4>
                      <p class="text-secondary mb-1">{{ user.email}}</p>
                      <button class="btn btn-outline-primary">Edit Profile</button>
                      
                    </div>
                  </div>
                </div>
              </div>
            
            </div>
            <div class="col-md-8">
              <div class="card" style="background-color: rgb(255, 255, 255); padding: 10px;">
              <div class="card mb-3">
                <div class="card-body" style="padding: 10px; margin: 10px;" >
                  <h3><i>Your Details</i></h3><hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">First Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{user.first_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Last Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{user.last_name}}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{user.email}}
                    </div>
                  </div>
                  <hr>
                    
                  
                  
                </div>
              </div>
              </div>
            </div>
                <!-- user's product -->
              
           



            
          </div>

        </div>
    
    <div class="row">
      <div class="card" style="background-color: rgb(255, 255, 255);">
        <div class="card-body" style="padding: 5px;margin: 10px;">

        <h3><i>Your Adds</i></h3>
      </div>
      </div>
       
       
    
      <div class="card" style="background-color: rgb(255, 255, 255);">
          
          {% for product in product_by_user %}
          
          <div class="col-md-3">
            <div class="mt-5">
           
                  <div class="about-product text-left mt-2"><img src='/media/{{product.image}}' style="width: 100%; height:170px">
                      <div class="card-body" style="padding: 5px;margin: 10px;">
                          <h3><i style="font-size:24px" class="fa">&#xf156;</i>{{product.product_price}}</h3>
                          <h6 class="mt-0 text-black-50">{{product.product_title}}</h6>
                          <div class="row">
                            <a href="{% url 'user:update_product' product.id %}" class="btn btn-primary">Update</a>&nbsp;
                                                              
                            
                            <a href="{% url 'user:delete_product' product.id %}" class="btn btn-primary">delete</a>
                            <a href="{% url 'user:detail_view' product.id %}" class="btn btn-primary">View</a>

                          </div>
                          
                      </div>
                  </div>
                                   
             </div>
            </div>
          
            {% endfor %}
       </div>
    </div>


    

      

   
</div>
   

<!-- </body>
</html> -->
{% endblock %}

olx/user/templates/user/register.html
{% extends "olx.html" %}

{% block content %}
<!-- <!DOCTYPE html>

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

</head>
<body>
 -->
 


<div  class="container border" >
  
  <div id="signup" style="display: block;">
    <div class="title_container"><h2>Registration</h2></div> 
  <form  class="was-validation" class="needs-validation"  novalidate>
    
    <div class="form-group">
      <label for="uname">First Name:</label>
      <input type="text" class="form-control" placeholder="Enter first name" name="first_name" maxlength="150" id="id_first_name" required>
     
      
    </div>
    <div class="form-group">
        <label for="uname">Last Name:</label>
        <input type="text" class="form-control" placeholder="Enter last name" name="last_name" maxlength="150" id="id_last_name" required>
        
        
      </div>
      <div class="form-group">
        <label for="uname">Email Address:</label>
        <input type="email" class="form-control" placeholder="Enter email id" name="email" maxlength="254" required="" id="id_email" required="required">
        
        
      </div>
      
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="id_password" placeholder="Enter password" name="password" required>
     
      
    </div>
    <div class="form-group">
        <label for="psw-repeat"><b>Repeat Password</b></label>
    <input type="password" class="form-control" placeholder="Repeat Password" name="password1" id="id_password1" required>
       
        
      </div>
    
    
    <button type="button" class="btn btn-primary" onclick="ajax_send_otp()">Next</button>
  </div> 

  <script>  </script>
    <!-- otp varification div -->
    <div id="otp" class="container border" style="display: none;">

        <div class="title_container"><h2>OTP varification</h2></div> 
        
        
          
          <div class="form-group">
            <label for="uname">OTP:</label>
            <input type="text" class="form-control" placeholder="Enter OTP" name="otp" maxlength="6" id="id_otp" required>
            <button type="button"  class="btn btn-primary" onclick="verify_otp()">Verify</button>
          </div>  
 
    </div>
   
    <!-- <div id="submit_btn" class="container border" style="display: none;">
      <button type="submit"  class="btn btn-primary" >submit</button>
    </div> -->
  </form>

 


  <script>
  

  // $("#id_email").change(function () {
  //             var email_text = $(this).val();
  //             console.log(email_text)
  //             $.ajax({
  //               url: 'validate_email/',
  //               data: {
  //                 'email_text': email_text
  //               },
  //               dataType: 'json',
  //               success: function (data) {
  //                 if (data.is_taken) {
                   
  //                   alert("A user with this email already exist.");
                    
  //                 }
  //               }
  //             });
        
  //           });


    // Disable form submissions if there are invalid fields
  


    // for ajax
    // var otp_from_back="";
    //  function ajax_send_otp(){
    //     document.getElementById("signup").style.display='block';
    //     email = document.getElementById("id_email");
    //     $.post("/send_otp",
    //       {
    //           "email":email.value,
    //           "csrfmiddlewaretoken":"{{csrf_token}}"
    //       },
    //       function(data, status){
    //           if(status=="success"){
    //               otp_from_back = data;
    //               console.log(otp_from_back)
    //               document.getElementById("otp").style.display='block';
    //               }
    //  }
    //  );
    //  }


function getCookie(c_name){
    if (document.cookie.length > 0){
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start != -1){
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
  }

var otp_from_back="";
function ajax_send_otp(){ 
  u_email = document.getElementById('id_email').value
  p1 = document.getElementById('id_password').value
  p2 = document.getElementById('id_password1').value
  fname = document.getElementById('id_first_name').value
  lname = document.getElementById('id_last_name').value
  console.log("function called")
   
    $.ajax({
      url : '/send_otp',
      type :'POST',
      headers: { "X-CSRFToken": getCookie("csrftoken") },
      dataType:'json',
      data : {
        'email' : u_email
      },
      success : function(data) {  
      document.getElementById("signup").style.display='none';
      otp_from_back = data;
      console.log(otp_from_back)
      document.getElementById("otp").style.display='block';
                
      // alert('Data: '+data);
      },
      error : function(request,error){
      alert('invalid data');
      }
  });
}

    // otp verification function
    function verify_otp(){
      var user_otp=document.getElementById("id_otp").value;
       
      $.ajax({
        url : '/verify_otp',
        type :'POST',
        headers: { "X-CSRFToken": getCookie("csrftoken") },
        dataType:'json',
        data : {
          'email' : u_email,
          'otp': user_otp
        },
        success : function(data) {  
          if (data == true)
            confirm_user();     
          else
            alert('invalid OTP');

        // alert('Data: '+data);
        },
        error : function(request,error){
        alert("Request: "+JSON.stringify(request));
        }
    });
    
    } 


function confirm_user(){ 
f_name = document.getElementById('id_first_name').value
l_name = document.getElementById('id_last_name').value
password = document.getElementById('id_password').value
$.ajax({
  url : '/confirm_user',
  type :'POST',
  headers: { "X-CSRFToken": getCookie("csrftoken") },
  dataType:'json',
  data : {
      'fname' : f_name,
      'lname' : l_name,
      'email' : u_email,
      'pwd' : password
   },
   success : function(data) {  

   alert('successfully register');
   window.location = "/login/";
    },
    error : function(request,error){
   alert("Request: "+JSON.stringify(request));
     }
   });
  }  

    </script>
</div>

<!-- </body>
</html> -->


{% endblock %}