olx/olx/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('user.urls')),
    path('admin/', admin.site.urls),
    path('paypal/', include('paypal.standard.ipn.urls')),
    #path('user/', include('django.contrib.auth.urls')),
   
]+  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx/user/urls.py
from atexit import register
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView

# importing views from views..py
app_name = 'user'
urlpatterns = [
    path('', views.home,name="home"),
    path('signup/',views.signup,name='signup'),   
    path('send_otp', views.send_otp, name='sendOTP' ),
    path('login/',views.login,name='login'),
    #path('signup/validate_email/', views.validate_email, name='validate_email'),
    path('logout/',views.logout,name='logout'),
    path('verify_otp', views.verify_otp, name='verify_otp' ),
    path('confirm_user', views.confirm_user, name='confirm_user' ),
    path('forget_password', views.forget_password, name='forget_password' ),
    path('setPassword', views.setPassword, name='setPassword' ),
    path('reset', views.reset, name='reset' ),
    path('reset_password', views.reset_password, name='reset_password' ),
    path('profile/', views.profile, name='profile' ),
    path('setting/', views.setting, name='setting' ),
    path('add_product/', views.add_product, name='add_product' ),
    path('product_by_category/<pk>', views.product_by_category,name="product_by_category"),
   # path('delete_product/<product_id>', views.delete_product.as_view(), name='delete_product' ),
    path('<pk>/delete_product', views.Delete_product.as_view(), name='delete_product' ),
    path('detail_view/<pk>', views.detail_view, name='detail_view' ),
    path('<pk>/update_product', views.update_product, name='update_product' ),
    path('<int:user_id>/<int:room_name>/<int:sender_id>/', views.room, name='room'),
  #  path('', views.index, name='index'),
    path('subscription', views.subscription, name='subscription' ),
    path('subscription_process/<pk>', views.subscription_process, name='subscription_process' ),
    path('message', views.message, name='message' ),
    path('payment_done/', views.payment_done,name='payment_done'),
    path('payment_cancelled/', views.payment_canceled, name='payment_cancelled'),
    path('seller_profile/<pk>', views.seller_profile, name='seller_profile' ),
    #path('search', views.SearchResultsView.as_view(), name='search_results'),
    path('search_product', views.search_product,name="search_product"),


    











   
] 

olx/user/models.py
from pyexpat import model
from sys import prefix
from unicodedata import category
import uuid
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# Create your models here.
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from .managers import CustomUserManager
from django.utils import timezone



class CustomUser(AbstractBaseUser, PermissionsMixin):
    user_choice=(('buyer','Buyer'),('seller','Seller'),)
    email = models.EmailField(('email address'), unique=True)
    first_name = models.CharField(blank=True, max_length=150, verbose_name='first name')
    last_name = models.CharField(blank=True, max_length=150, verbose_name='last name')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    user_type = models.CharField(max_length=20, choices= user_choice , default='buyer')
    objects = CustomUserManager()

    def __str__(self):
        return self.email

    # def save(self, *args, **kwargs):
    #     if not self.is_superuser:
    #         self.set_password(self.password)
    #         self.save()
    #     return super(CustomUser, self).save(force_insert=False,
    #                                   force_update=False,
    #                                   using=None,
    #                                   update_fields=None)


class EmailVerifyOtp(models.Model):
    email = models.EmailField(max_length=50, null=True, blank=True)
    otp = models.CharField(max_length=10, blank=True, null=True)


class Category(models.Model):
    categories=models.CharField(max_length=50,null=True, blank=True)
        
    def __str__(self):
        return self.categories

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    sub_categories=models.CharField(max_length=50,null=True, blank=True)

    def __str__(self):
        return self.sub_categories

        
class Product(models.Model):
   
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    category = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
    product_title=models.CharField(max_length=150,null=True, blank=True)
    product_description=models.CharField(max_length=150,null=True, blank=True)
    product_price=models.CharField(max_length=150,null=True, blank=True)
    product_location=models.CharField(max_length=150,null=True, blank=True)
    image=models.ImageField(upload_to='product_img',null=True, blank=True)

    def __str__(self):
        return self.product_title

    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product_img',null=True, blank=True)

    def __str__(self):
        return self.product.product_title

class SubscriptionBase(models.Model):
    subscription_choice=(('monthly','Monthly'),('annual','Annual'),)
    subscription = models.CharField(max_length=20, choices= subscription_choice,null=True, blank=True  )
    days=models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.subscription

class SubscriptionType(models.Model):
   # subscription_choice=(('monthly','Monthly'),('annual','Annual'),)
    name_choice=(('basic','Basic'),('standard','Standard'),('premium','Premium'))
   # subscription_name=  models.CharField(max_length=20, choices=  subscription_choice )
    package_name= models.CharField(max_length=20, choices= name_choice )
    price= models.FloatField(max_length=20, null=True, blank=True )
    ads_count=models.IntegerField(null=True, blank=True)
    subscription_name=models.ForeignKey(SubscriptionBase, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return self.package_name


class SubscriptionTransaction(models.Model):
    status_choice=(('initialized','Initialized'),('success','Success'),('failed','Failed')) 
    transaction_id=models.CharField(max_length=16,primary_key = True)
    amount= models.FloatField(max_length=20, null=True, blank=True )
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    transaction_status=models.CharField(max_length=20,choices=status_choice, default='initialized')
    invoice_id=models.CharField(max_length=16,null=True, blank=True)
    package=models.ForeignKey(SubscriptionType, on_delete=models.CASCADE,null=True)
    transaction_date=models.DateField(null=True,blank=True)

      

class UserSubscription(models.Model):
    user=models.ForeignKey(CustomUser, on_delete=models.CASCADE,null=True)
    transaction=models.ForeignKey(SubscriptionTransaction,on_delete=models.CASCADE,null=True)
    purchase_date=models.DateField(null=True,blank=True)
    valid_till=models.DateField(null=True,blank=True)
    package=models.ForeignKey(SubscriptionType, on_delete=models.CASCADE,null=True)


class ChatRoom(models.Model):
    product_id=models.ForeignKey(Product, on_delete=models.CASCADE,null=True)
    buyer=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='buyer',null=True)
    seller=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='seller',null=True)


class ChatHistory(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE)
    sender=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='sender',null=True)
    message=models.CharField(max_length=500,null=True,blank=True)
    receiver=models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='receiver',null=True)

olx/user/forms.py
# import the standard Django Forms
# from built-in library
from curses import meta
from pyexpat import model
from secrets import choice
from django import forms

from user.models import Product, Category, ProductImage, Subcategory



class InputForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Subcategory.objects.all())
    class Meta:
        model= Product
        fields = ['product_title', 'product_price','product_description','category','product_location','image']
    
   
class UpdateForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Subcategory.objects.all())
    class Meta:
        model= Product
        fields = ['product_title', 'product_price','product_description','category','product_location','image']


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')    
    class Meta:
        model = ProductImage
        fields = ('image', )

olx/user/templates/add_product.html
{% extends "olx.html" %}

{% block content %}

<!-- <form method="post">
{% csrf_token %}
 
  
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form> -->
<div class="container">
    <form class="text-center border border-light p-5" method="POST" action=""enctype="multipart/form-data">
        {% csrf_token %}  
        
        
            <!-- <input type="text" id="user_id" class="form-control mb-4"name="user" value=""><br> -->
            
            <input type="text" id="product_title_id" class="form-control mb-4"name="product_title" placeholder="Product title"><br>
            <input type="text" id="price_id" class="form-control mb-4"name="product_price" placeholder="Product Price"><br>
            <textarea class="form-control mb-4" name="product_description" id="product_description_id" rows="3"placeholder="Product Description"></textarea><br>
            <input type="text" id="product_location_id" class="form-control mb-4"name="product_location" placeholder="location"><br>

            <select class="form-control mb-4"name="category" id="id_category">
                <option selected disabled>Select Category</option>
               
                {% for choice in form.category.field.queryset %}
               
                <option value=" {{ choice.pk }}"> {{ choice.sub_categories }}</option>
                {% endfor %}
                
               
               
            
                </select><br>
            <input type="file" id="image_id" class="form-control mb-4"name="image"><br>
        
     
           
            <button class="btn btn-info btn-block" type="submit">Save</button>

            
        
        </form>
       
</div>

{% endblock %}

olx/user/templates/login.html
{% extends "olx.html" %}

{% block content %}
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body> -->

<div class="container">
  <h2>LogIn</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email:</label>
      <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    </div>
    <div class="form-group">
      <label for="pwd">Password:</label>
      <input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
    </div>
    <!-- <div class="form-group form-check">
      <label class="form-check-label">
        <input class="form-check-input" type="checkbox" name="remember"> Remember me
      </label>
    </div> -->
    <a href="/forget_password" style="float:right;font-size:12px;"> Forgot password? </a>  
    <button type="submit" class="btn btn-primary">Log In</button>
    <a href="/signup"> <button type="button" class="btn btn-primary">Register</button></a>
  </form>
</div>
<!-- 
</body>
</html> -->
{% endblock %}

olx/user/templates/olx.html
<!-- <ul>
{% if user.is_authenticated %}
<li>hello,{{user.first_name}}</li>
<li> <a href="logout"> logout</a></li>
{% else %}
<li><a href="login">please login</a></li>

{% endif %}
</ul> -->

<!DOCTYPE html>
<html lang="en">
<head>
  <title>OLX</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
body {
  /* background: #ff5f6d;
  background: -webkit-linear-gradient(to right, #00001a, #00004d);
  background: linear-gradient(to right, #00001a, #00004d); */
  min-height: 100vh;
  font-family: 'Sanchez', serif;
  
}

#button-addon1 {
  color: #ffc371;
}

/* i {
  color: #0000cc;
  font-size: 20px;} */

.form-control::placeholder {
  font-size: 0.95rem;
  color: #aaa;
  font-style: italic;
}

.form-control.shadow-0:focus {
  box-shadow: none;
}

 
.display-3{
  font-family: 'Sanchez', serif;
}

p{
  font-family: 'Tajawal', sans-serif;
}

.lead{
  font-family: 'Sanchez 200', serif;
}
#footer {
            /* position: fixed; */
            padding: 20px 20px 0px 20px;
            bottom: 0;
            width: 100%;
            /* Height of the footer*/ 
            height: 200px;
            
        }
        .topnav .search-container {
  float: right;
}

.navbar input[type=text] {
  padding: 6px;
  margin-top: 8px;
  font-size: 17px;
  border: none;
}

.navbar .search-container button {
  float: right;
  padding: 6px 10px;
  margin-top: 8px;
  margin-right: 16px;
  background: #ddd;
  font-size: 17px;
  border: none;
  cursor: pointer;
}

.navbar .search-container button:hover {
  background: #ccc;
}

  </style>
</head>
<body  style="background-color:rgb(235, 245, 255) ;">

<nav class="navbar " style="background-color: rgb(146, 199, 251) ;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">OLX</a>
    
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
    </div>  
    
  </ul>
    <ul class="nav navbar-nav navbar-right">
      <li>
        <div class="search-container">
          <form action="{% url 'user:search_product' %}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="Search.." name="search">
            <button type="submit"><i class="fa fa-search"></i></button>
          </form>
        </div>
        
      </li>
      {% if user.is_authenticated %}
      <li><a href="/message"><span class="glyphicon glyphicon-envelope"></span> Messages</a></li>
      <li><a href="{% url 'user:add_product' %}"><span class="glyphicon glyphicon-plus"></span> Sell</a></li>
      <li class="dropdown"><a class="dropdown-toggle glyphicon glyphicon-user" data-toggle="dropdown" href="#">hello,{{user.first_name}} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url 'user:profile' %}">Profile</a></li>
          <li> <a href="{% url 'user:setting' %}"> Settings</a></li>
          <li> <a href="{% url 'user:logout' %}"> logout</a></li>
         
         
        </ul>
      </li>
      {% else %}
      <li><a href="/signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="{% url 'user:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      
      {% endif %}
    </ul>
  </div>
</nav>
{% for message in messages %}
    
 <div class="alert alert-success">
     <a class="close" href="#" data-dismiss="alert">x</a>
        {{ message }}
 </div>

{% endfor %}


{% block content %}

{% endblock %}
<br><br>


<div id="footer">
  <footer class="bg-white">
    <div class="container py-5">
      <div class="row py-3">

        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">About</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="#" class="text-muted">Contact Us</a></li>
            <li class="mb-2"><a href="#" class="text-muted">About Us</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Stories</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Press</a></li>
          </ul>
        </div>

        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Help</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="#" class="text-muted">Payments</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Shipping</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Cancellation</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Returns</a></li>
          </ul>
        </div>
        
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Policy</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="#" class="text-muted">Return Policy</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Terms Of Use</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Security</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Privacy</a></li>
          </ul>
        </div>
        <div class="col-lg-2 col-md-6 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Company</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="#" class="text-muted">Login</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Register</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Sitemap</a></li>
            <li class="mb-2"><a href="#" class="text-muted">Our Products</a></li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Registered Office Address</h6>
          <p class="text-muted mb-4">Here , write the complete address of the Registered office address along with telephone number.</p>
          <ul class="list-inline mt-4">
            <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fab  fa-2x fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i class="fab fa-2x fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fab fa-2x fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fab fa-2x fa-youtube"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="vimeo"><i class="fab fa-2x fa-google"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
    <hr class="p-0 m-0 b-0">

   
    <div class="bg-light py-2">
      <div class="container text-center">
        <p class="text-muted mb-0 py-2">&copy; 2019 BBBootstrap All risghts reserved.</p>
        
        </div>
      </div>
    
  </footer>
</div>

</body>
</html>

olx/user/templates/search_product.html
{% extends "olx.html" %}
<!-- <ul>
{% if user.is_authenticated %}
<li>hello,{{user.first_name}}</li>
<li> <a href="logout"> logout</a></li>
{% else %}
<li><a href="login">please login</a></li>

{% endif %}
</ul> -->
{% load static %}
{% block content %}
<style>

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  background-color: rgb(255, 255, 255);
  max-width: 300px;
  margin: auto;
  padding: auto;
  /* text-align: center; */
  font-family: arial;
}
</style>
<div class="container">
<nav aria-label="breadcrumb" class="main-breadcrumb">
  <ol class="breadcrumb">
    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">All Categories <span class="caret"></span></a>
      <ul class="dropdown-menu">
                 
      
      {% for cat in categorylist %}
      
      <li><a href="{% url 'user:product_by_category' cat.id %}" value="{{cat.id}}">{{cat.sub_categories}}</a></li>
      {% endfor %}
      
      
              

      </ul>
    </li>
  </ol>
</nav>
</div>
<div class="container-fluid">
<div class="row">

{% for product in productlist %}
<!-- <div class="card" style="width:400px">
  <img class="card-img-top" src='/media/{{product.image}}' alt="Card image" style="width:100%">
  <div class="card-body">
    <h4 class="card-title">{{product.product_title}}</h4>
    <p class="card-text">{{product.product_description}}</p>
    
  </div>
</div> -->
<div class="col-md-2">
<div class="mt-5">
  <div class="card">
      <div class="about-product text-left mt-2"><img src='/media/{{product.image}}' style="width: 100%; height:250px">
        <div class="card-body" style="padding: 10px; margin: 10px; ">
          <h3 class="card-title"><i style="font-size:24px" class="fa">&#xf156;</i>{{product.product_price}}</h3>
              <!-- <h3><i style="font-size:24px" class="fa">&#xf156;</i>{{product.product_price}}</h3> -->
              <h4 class="mt-0 text-black-50 card-text">{{product.product_title}}</h4>
              <a href="{% url 'user:detail_view' product.id %}" class="btn btn-primary">View</a>
            

             

          </div>
      </div>
      
    </div>   
</div>
</div>






{% endfor %}
</div>
</div>
{% endblock %}
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Home</a></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><a href="#">Page 2</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      
      {% if user.is_authenticated %}
      <li></li>
      <li class="dropdown"><a class="dropdown-toggle glyphicon glyphicon-user" data-toggle="dropdown" href="#">hello,{{user.first_name}} <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="profile">Profile</a></li>
          <li> <a href="settings"> Settings</a></li>
          <li> <a href="logout"> logout</a></li>
         
         
        </ul>
      </li>
      {% else %}
      <li><a href="signup"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
  
<div class="container">
  
</div>

</body>
</html> -->

olx/user/templates/update_product.html
{% extends "olx.html" %}

{% block content %}
<div class="container">
<form method="post">
    {% csrf_token %}
     
    
    {{ form.as_p }}
    <input type="submit" value="Update">
    <!-- <input type="text" id="product_title_id" class="form-control mb-4"name="product_title" value="{{products.product_title}}"><br>
    <input type="text" id="price_id" class="form-control mb-4"name="product_price" value="{{products.product_price}}" ><br>
    <textarea class="form-control mb-4" name="product_description" id="product_description_id" value="{{products.product_description}}" rows="3"></textarea><br>
    <input type="text" id="product_location_id" class="form-control mb-4"name="product_location" value="{{products.product_location}}"><br>

    <select class="form-control mb-4"name="category" id="id_category">
        <option selected disabled>Select Category</option>
       
        {% for choice in form.category.field.queryset %}
       
        <option value=" {{ products.category }}"> {{ choice.sub_categories }}</option>
        {% endfor %}
    
    </select><br>
    <input type="file" id="image_id" class="form-control mb-4"name="image" value="{{products.image}}"><br>
    <input type="submit" value="Update">
</form> -->
</div>

{% endblock %}